### ISSUE TITLE
As an Administrator, I want to be able to create pages for my site

### ISSUE THREAD

**Issue by robyurkowski** [grounded/afterburnercms#5]
I want to be able to add pages with content through a web interface.

**Comment by knewter** [comment]
So here's a fun question, and maybe the place to discuss it.  Once we layer on wysiwyg (not in MVP imo, should definitely be in a plugin, as should pages itself likely), etc....

What should we use for the wysiwyg piece?  This looks neat but I haven't used it:

http://imperavi.com/redactor/

I know that @parndt has some feelings in this area, or likely does.

**Comment by nicinabox** [comment]
I have some feelings in this area. I've been using Redactor a lot recently. Let me give some honest feedback on it.

**It's not open source.** This is both good and bad. They release updates fairly regularly, which is great. Getting a bug fixed or getting support is downright impossible. You need to pay for a license to use it in your project.

**It doen't follow common Javascript conventions.** The codebase is super awkward to work with if you need to fix bugs yourself. Oh and if you have fixed a bug and you want to update, you'll need to port those changes to the new version. 

**The plugin system is mediocre.** Since it's not open source, there's really no community around it aside from people here or there saying "Yeah, Redactor is great!". It doesn't live up to the hype in my opinion.

When you really boil it down, all wysiwygs have the same types of problems. They don't work well crossbrowser, the dependencies out of control, or the code turns to spaghetti unmanageable by anyone outside of the core authors, and they try to do EVERYTHING.

## 

**I propose a different approach.** I've been working on a prototype for a layout engine called Harmony ([you can read the proposal I wrote up for it internally here](https://gist.github.com/nicinabox/bf95afa8e06cb655ff66)). The idea is that a text editor shouldn't handle layouts. That's a job for a layout engine. So, you pick from different content blocks (text, image, video, code embed, whatever) and drag them around to create the layout. You can use any text editor you want, because all it really cares about is rows, columns, and floats.

**Comment by knewter** [comment]
So honestly, I didn't realize redactor wasn't open source.  That already strikes it from the list of useful software in my boat.  Looking at Harmony now

**Comment by nicinabox** [comment]
I think there might me some old version of it that is open source. I'm not sure that it would be worth using though.

**Comment by knewter** [comment]
so I'm going to have a look at this atm.  If you don't hear from me within a few hours I got distracted by family and no one should expect I'm still pushing it forward :)

**Comment by robyurkowski** [comment]
I'd consider this a success by @knewter. Right on!
